import matplotlib.pyplot as plt

def update_rcParams():
    plt.rcParams.update({
        'font.family': 'serif',
        'font.serif': ['FreeSerif'],
        'font.size': 12,
        'axes.titlesize': 14,
        'axes.labelsize': 12,
        'xtick.labelsize': 10,
        'ytick.labelsize': 10,
        'legend.fontsize': 10,
        'figure.figsize': (8, 6),
        'figure.dpi': 300,
        'savefig.dpi': 300,
        'axes.linewidth': 0.8,
        'grid.linewidth': 0.5,
        'lines.linewidth': 1.5,
        'lines.markersize': 6,
        'legend.frameon': True,
        'legend.framealpha': 0.8,
        'legend.edgecolor': 'black',
        'legend.fancybox': False,
        'legend.loc': 'best',
        'grid.alpha': 0.7,
        'grid.linestyle': '--',
        'grid.color': 'gray',
        'axes.grid': True,
        'axes.grid.which': 'both',
        'xtick.direction': 'in',
        'ytick.direction': 'in',
        'xtick.major.size': 5,
        'ytick.major.size': 5,
        'xtick.minor.size': 3,
        'ytick.minor.size': 3,
        'xtick.major.width': 0.8,
        'ytick.major.width': 0.8,
        'xtick.minor.width': 0.6,
        'ytick.minor.width': 0.6,
        'axes.spines.top': False,
        'axes.spines.right': False,
        'axes.spines.left': True,
        'axes.spines.bottom': True,
        'axes.labelpad': 10,
        'axes.titlepad': 15,
        'figure.autolayout': True
    })